env_name: run-to-goal-ants-v0

runner_type: multi-agent-runner 

# training parameters
gamma: 0.995
tau: 0.95
policy_specs:
  name: v5
  htype: tanh
  control_mlp:
    hdims: [128, 128]
    rescale_linear: true
  control_log_std: 0
  fix_control_std: false
policy_optimizer: 'Adam'
policy_lr: 5.e-5 #5.e-5
policy_momentum: 0.0
policy_weightdecay: 0.0
value_specs:
  htype: tanh
  mlp: [512, 256]
value_optimizer: 'Adam'
value_lr: 3.e-4 #3.e-4
value_momentum: 0.0
value_weightdecay: 0.0
clip_epsilon: 0.2
min_batch_size: 50000 #50000
mini_batch_size: 2048 #2048
num_optim_epoch: 10 #10
max_epoch_num: 1000
seed: 3
save_model_interval: 1

done_condition:
  max_ang: 60

use_reward_scaling: False
use_opponent_sample: True
delta: 1

use_exploration_curriculum: False
termination_epoch: 1000

use_parse_reward: True